In [16]:
import numpy as np
def step(x):
    return 1 if x >= 0 else 0
def neuron(inputs, weights, bias):
    return step(np.dot(inputs, weights) + bias)

In [17]:
def OR_P(inputs):
    return neuron(inputs, np.array([1, 1]), -1)

## NOT Gate
def NOT_P(input):
    return neuron(input, np.array([-1]), 0)

## AND Gate
def AND_P(inputs):
    return neuron(inputs, np.array([1, 1]), -2)

## XOR Gate V2
def XOR_P(inputs):
    n1 = neuron(inputs, np.array([1, 1]), -1)
    n2 = neuron(inputs, np.array([-1, -1]), 1)
    n3 = neuron([n1, n2], np.array([1, 1]), -2)
    return n3

In [18]:
inputsList = [[a, b] for a in range(2) for b in range(2)]
np_inputsList = np.array(inputsList)
for x in np_inputsList:
    print(f"AND_P({x}) = {AND_P(x)}")

print("-" * 50)

inputList = [0 ,1]
np_inputList = np.array(inputList)
for x in np_inputList:
    print(f"NOT_P({x}) = { NOT_P(x)}")

print("-" * 50)

for x in np_inputsList:
    print(f"OR_P({x}) = { OR_P(x)}")

print("-" * 50)

for x in np_inputsList:
    print(f"XOR_P({x}) = { XOR_P(x)}")

AND_P([0 0]) = 0
AND_P([0 1]) = 0
AND_P([1 0]) = 0
AND_P([1 1]) = 1
--------------------------------------------------
NOT_P(0) = 1
NOT_P(1) = 0
--------------------------------------------------
OR_P([0 0]) = 0
OR_P([0 1]) = 1
OR_P([1 0]) = 1
OR_P([1 1]) = 1
--------------------------------------------------
XOR_P([0 0]) = 0
XOR_P([0 1]) = 1
XOR_P([1 0]) = 1
XOR_P([1 1]) = 0


In [19]:
def MLP_P(inputs):
    n1 = neuron(inputs[[1, 2]], np.array([1, 1]), -2)
    n2 = neuron(inputs[[1, 3]], np.array([1, 1]), -2)
    n3 = neuron(inputs[[0, 2]], np.array([1, -1]), -1)
    n4 = neuron(inputs[[0, 1, 3]], np.array([1, -1, 1]), -2)
    n5 = neuron(np.array([[n3, n4]]), np.array([1, 1]), -1)
    n6 = neuron(np.array([[n1, n2]]), np.array([1, -1]), 0)
    n7 = neuron(np.array([[n5, n6]]), np.array([1, 1]), -2)
    return n7

def MLP_EXP(inputs):
    return ((inputs[0] and not inputs[1] and inputs[3]) or (inputs[0] and not inputs[2])) and ((inputs[1] and inputs[2]) or not (inputs[1] and inputs[3]))


In [20]:
inputs = [[a, x, y, z] for a in range(2) for x in range(2) for y in range(2) for z in range(2)]
np_inputs = np.array(inputs)
for x in np_inputs:
    print(f"MLP_P({x}) = { MLP_P(x)} -> {bool(MLP_EXP(x))}")

MLP_P([0 0 0 0]) = 0 -> False
MLP_P([0 0 0 1]) = 0 -> False
MLP_P([0 0 1 0]) = 0 -> False
MLP_P([0 0 1 1]) = 0 -> False
MLP_P([0 1 0 0]) = 0 -> False
MLP_P([0 1 0 1]) = 0 -> False
MLP_P([0 1 1 0]) = 0 -> False
MLP_P([0 1 1 1]) = 0 -> False
MLP_P([1 0 0 0]) = 1 -> True
MLP_P([1 0 0 1]) = 1 -> True
MLP_P([1 0 1 0]) = 0 -> False
MLP_P([1 0 1 1]) = 1 -> True
MLP_P([1 1 0 0]) = 1 -> True
MLP_P([1 1 0 1]) = 0 -> False
MLP_P([1 1 1 0]) = 0 -> False
MLP_P([1 1 1 1]) = 0 -> False


In [21]:
def frequency(lst):
    freq = []
    counter = 1
    i = 0
    while i < len(lst) - 1:
        if lst[i] == lst[i + 1]:
            counter += 1
        else:
            freq.append(counter)
            counter = 1
        i += 1
    freq.append(counter)
    return freq


test = [1, 1, 1, 2, 3, 4, 4, 4]

freqs = frequency(test)

s = 0
j = 0
while j < len(freqs):
    print(f"[{test[s]} : {freqs[j]}]")
    s += freqs[j]
    j += 1


[1 : 3]
[2 : 1]
[3 : 1]
[4 : 3]


In [22]:
def EXP_P(inputs):
    n1 = neuron(inputs[[2, 3]], np.array([-1, -1]), 0)
    n2 = neuron(inputs[[0, 1, 2]], np.array([-1, 1, -1]), -1)
    n3 = neuron(inputs[[1, 3]], np.array([-1, -1]), 0)
    n4 = neuron(np.array([n1, n2, n3]), np.array([1, 1, 1]), -1)
    return n4
def TEST_EXP(inputs):
    w, x, y, z = inputs
    return not y and not z or not w and x and not y or not x and not z;

arr = [[w, x, y, z] for w in range(2) for x in range(2) for y in range(2) for z in range(2)]
arr2 = np.array(arr)
for x in arr2:
    print(f"EXP_P({x}) = {EXP_P(x)} -> {TEST_EXP(x)}")




EXP_P([0 0 0 0]) = 1 -> True
EXP_P([0 0 0 1]) = 0 -> False
EXP_P([0 0 1 0]) = 1 -> True
EXP_P([0 0 1 1]) = 0 -> False
EXP_P([0 1 0 0]) = 1 -> True
EXP_P([0 1 0 1]) = 1 -> True
EXP_P([0 1 1 0]) = 0 -> False
EXP_P([0 1 1 1]) = 0 -> False
EXP_P([1 0 0 0]) = 1 -> True
EXP_P([1 0 0 1]) = 0 -> False
EXP_P([1 0 1 0]) = 1 -> True
EXP_P([1 0 1 1]) = 0 -> False
EXP_P([1 1 0 0]) = 1 -> True
EXP_P([1 1 0 1]) = 0 -> False
EXP_P([1 1 1 0]) = 0 -> False
EXP_P([1 1 1 1]) = 0 -> False


In [33]:
def XOR_L(inputs):

    result = XOR_P(inputs[[0,1]])
    for x in range(2, len(inputs)):
        result = XOR_P(np.array([inputs[x], result]))

    return result

list_test = [[a, b, c, d, f] for a in range(2) for b in range(2) for c in range(2) for d in range(2) for f in range(2)]
np_inputs = np.array(list_test)

for x in np_inputs:
    print(f"XOR_L({x}) = {XOR_L(x)}")




XOR_G([0 0 0 0 0]) = 0
XOR_G([0 0 0 0 1]) = 1
XOR_G([0 0 0 1 0]) = 1
XOR_G([0 0 0 1 1]) = 0
XOR_G([0 0 1 0 0]) = 1
XOR_G([0 0 1 0 1]) = 0
XOR_G([0 0 1 1 0]) = 0
XOR_G([0 0 1 1 1]) = 1
XOR_G([0 1 0 0 0]) = 1
XOR_G([0 1 0 0 1]) = 0
XOR_G([0 1 0 1 0]) = 0
XOR_G([0 1 0 1 1]) = 1
XOR_G([0 1 1 0 0]) = 0
XOR_G([0 1 1 0 1]) = 1
XOR_G([0 1 1 1 0]) = 1
XOR_G([0 1 1 1 1]) = 0
XOR_G([1 0 0 0 0]) = 1
XOR_G([1 0 0 0 1]) = 0
XOR_G([1 0 0 1 0]) = 0
XOR_G([1 0 0 1 1]) = 1
XOR_G([1 0 1 0 0]) = 0
XOR_G([1 0 1 0 1]) = 1
XOR_G([1 0 1 1 0]) = 1
XOR_G([1 0 1 1 1]) = 0
XOR_G([1 1 0 0 0]) = 0
XOR_G([1 1 0 0 1]) = 1
XOR_G([1 1 0 1 0]) = 1
XOR_G([1 1 0 1 1]) = 0
XOR_G([1 1 1 0 0]) = 1
XOR_G([1 1 1 0 1]) = 0
XOR_G([1 1 1 1 0]) = 0
XOR_G([1 1 1 1 1]) = 1


In [31]:
def XOR_I(inputs):
    newInput = np.array(inputs)
    while len(newInput) > 1:
        xor_list = []
        for x in range(0, len(newInput) - 1, 2):
            result = XOR_P(newInput[[x, x + 1]])
            xor_list.append(result)

        if len(newInput) % 2 == 1:
            xor_list.append(newInput[-1])

        newInput = np.array(xor_list)
    return newInput[0]

for x in np_inputs:
    print(f"XOR_I({x}) = {XOR_I(x)}")





XOR_I([0 0 0 0 0]) = 0
XOR_I([0 0 0 0 1]) = 1
XOR_I([0 0 0 1 0]) = 1
XOR_I([0 0 0 1 1]) = 0
XOR_I([0 0 1 0 0]) = 1
XOR_I([0 0 1 0 1]) = 0
XOR_I([0 0 1 1 0]) = 0
XOR_I([0 0 1 1 1]) = 1
XOR_I([0 1 0 0 0]) = 1
XOR_I([0 1 0 0 1]) = 0
XOR_I([0 1 0 1 0]) = 0
XOR_I([0 1 0 1 1]) = 1
XOR_I([0 1 1 0 0]) = 0
XOR_I([0 1 1 0 1]) = 1
XOR_I([0 1 1 1 0]) = 1
XOR_I([0 1 1 1 1]) = 0
XOR_I([1 0 0 0 0]) = 1
XOR_I([1 0 0 0 1]) = 0
XOR_I([1 0 0 1 0]) = 0
XOR_I([1 0 0 1 1]) = 1
XOR_I([1 0 1 0 0]) = 0
XOR_I([1 0 1 0 1]) = 1
XOR_I([1 0 1 1 0]) = 1
XOR_I([1 0 1 1 1]) = 0
XOR_I([1 1 0 0 0]) = 0
XOR_I([1 1 0 0 1]) = 1
XOR_I([1 1 0 1 0]) = 1
XOR_I([1 1 0 1 1]) = 0
XOR_I([1 1 1 0 0]) = 1
XOR_I([1 1 1 0 1]) = 0
XOR_I([1 1 1 1 0]) = 0
XOR_I([1 1 1 1 1]) = 1


In [38]:
def XOR_R(inputs):
    newInput = np.array(inputs)
    if len(newInput) == 1:
        return newInput[0]

    xor_list = []
    for x in range(0, len(newInput) - 1, 2):
        result = XOR_P(newInput[[x, x + 1]])
        xor_list.append(result)

    if len(newInput) % 2 == 1:
        xor_list.append(newInput[-1])

    newInput = np.array(xor_list)
    return XOR_R(newInput)

for x in np_inputs:
    print(f"{x} -> Linear={XOR_L(x)}, Iterative={XOR_I(x)}, Recursive={XOR_R(x)}")






[0 0 0 0 0] -> Linear=0, Iterative=0, Recursive=0
[0 0 0 0 1] -> Linear=1, Iterative=1, Recursive=1
[0 0 0 1 0] -> Linear=1, Iterative=1, Recursive=1
[0 0 0 1 1] -> Linear=0, Iterative=0, Recursive=0
[0 0 1 0 0] -> Linear=1, Iterative=1, Recursive=1
[0 0 1 0 1] -> Linear=0, Iterative=0, Recursive=0
[0 0 1 1 0] -> Linear=0, Iterative=0, Recursive=0
[0 0 1 1 1] -> Linear=1, Iterative=1, Recursive=1
[0 1 0 0 0] -> Linear=1, Iterative=1, Recursive=1
[0 1 0 0 1] -> Linear=0, Iterative=0, Recursive=0
[0 1 0 1 0] -> Linear=0, Iterative=0, Recursive=0
[0 1 0 1 1] -> Linear=1, Iterative=1, Recursive=1
[0 1 1 0 0] -> Linear=0, Iterative=0, Recursive=0
[0 1 1 0 1] -> Linear=1, Iterative=1, Recursive=1
[0 1 1 1 0] -> Linear=1, Iterative=1, Recursive=1
[0 1 1 1 1] -> Linear=0, Iterative=0, Recursive=0
[1 0 0 0 0] -> Linear=1, Iterative=1, Recursive=1
[1 0 0 0 1] -> Linear=0, Iterative=0, Recursive=0
[1 0 0 1 0] -> Linear=0, Iterative=0, Recursive=0
[1 0 0 1 1] -> Linear=1, Iterative=1, Recursive=1
